-- Supabase schema for PrepMind interview workflow

create extension if not exists "pgcrypto";

-- Core interviews table (matches app expectations)
create table if not exists public.interviews (
  id bigint generated by default as identity primary key,
  title text not null,
  created_at timestamptz default now()
);

insert into public.interviews (title)
select 'AI Interview 1'
where not exists (select 1 from public.interviews limit 1);

-- Enable Row Level Security
alter table public.interviews enable row level security;

-- Policies
create policy if not exists "Allow insert" on public.interviews for insert with check (true);
create policy if not exists "Allow read" on public.interviews for select using (true);
